### ISSUE TITLE
Texto no Formulário de Avaliação Gratuita

### ISSUE THREAD

**Issue by renatocfrancisco** [FronteiraTec/sem-fronteiras#45]
Se eu adiciono um texto nos campos do formulário por "preenchimento automático", o texto aparece.
Mas se eu escrevo nos campos, o texto é inserido mas não é visível.

**Comment by ghost** [comment]
galera, vou corrigir isso. Só terminar a parte que eu estou fazendo agora e dps eu ja volto nessa e resolvo
